# Generated by Django 5.2.6 on 2025-09-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_roomtype_roombooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Total rooms available for this type'),
        ),
    ]
