# Generated by Django 5.2.6 on 2025-09-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_food_room_tour_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
