# Generated by Django 5.2.6 on 2025-09-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_activity_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='pax',
        ),
    ]
