# Generated by Django 5.2.6 on 2025-09-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_rename_guests_booking_pax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
