# Generated by Django 5.2.6 on 2025-09-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_tour_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='price',
            new_name='price_per_person',
        ),
    ]
