# Generated by Django 5.2.6 on 2025-09-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pax_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
