# Generated by Django 5.2.6 on 2025-09-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_booking_pax_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Epic Trail Adventure Park', max_length=100)),
                ('support_email', models.EmailField(default='support@example.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('enable_mpesa', models.BooleanField(default=True)),
                ('enable_stripe', models.BooleanField(default=False)),
                ('max_daily_bookings', models.PositiveIntegerField(default=100)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
