# Generated by Django 5.2.6 on 2025-09-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_systemsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='price',
            new_name='price_per_person',
        ),
    ]
