# Generated by Django 5.2.6 on 2025-09-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_foodorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
